import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import NavBar from './components/NavBar/NavBar';
import ReactQueryProvider from '@/util/Providers';
import AuthSessionProvider from '@/util/SessionProvider';
import {getServerSession} from 'next-auth';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <AuthSessionProvider session={session}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavBar />
          <div className='container mx-auto'>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </div>
        </body>
      </AuthSessionProvider>
    </html>
  );
}
