import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.scss';
import NavBar from './components/NavBar/NavBar';
import ReactQueryProvider from '@/util/Providers';
import {QuizStoreProvider} from '@/util/quiz-store-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className='container mx-auto'>
          <QuizStoreProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </QuizStoreProvider>
        </div>
      </body>
    </html>
  );
}
